### PR TITLE
fix tests directory shouldn't have init.py

### PR DESCRIPTION
**Pull request by robvdl**
The tests directory shouldn't have an `__init.py__` and the imports into your package should just use the package name not `src.packagename`.

See: https://docs.pytest.org/en/7.1.x/explanation/goodpractices.html#tests-outside-application-code

I've ran the tests locally in a virtualenv to verify it works, and the tests passed locally.

### CODE REVIEW

**Comment by robvdl** [comment]
The extra blank lines is so that it conforms to isort.

"time" is standard library and belongs in the first group

"pytest" is third party so belongs in the next group

"thread" is your code so belongs in the next group

I normally wouldn't do multiple things in one commit, but I was already touching those lines anyway.

**Comment by robvdl** [comment]
OK so the tests are passing for me locally but not in CI/CD so you have something off with your CI setup.

The import "thread" should work. You shouldn't have to import it through src, if you are doing that, it's wrong.

image

Need to inspect the CI setup next, that is where the problem will lie.

**Comment by caffeine-addictt** [comment]
CI tests are ran from the CLI
```sh
python -m pytest -sv
```

I don't believe this behavior would differ. At least for me, its also failing locally.

**Comment by robvdl** [comment]
If I install it like this it works by the way:

    pip install .

But that won't install the dev dependencies, and `pip install .[dev]` doesn't work.

you could install the dev dependencies manually then run `pip install .`, but I don't understand the whole dance in using poetry to export a requirements.txt then install from that requirements.txt

checkout github.com/wainuiomata/sambal, pyproject.toml that is not using poetry

but I do have some other projects that do use poetry, just not open source

**Comment by robvdl** [comment]
See what I mean, that second commit just runs "pip install ." and it magically starts working.

This is what I mean something seems off with the poetry install, I run "poetry install" on my project and it installs the module. I run "poetry install" on your project and it doesn't.

We could compare pyproject.toml I guess, but running "pip install ." is a quick fix.

**Comment by caffeine-addictt** [comment]
This is quite odd behavior. `poetry install` does install thread locally for me but doesn't seem to in CI. That why dependencies were installed through the generated requirements.

**Comment by robvdl** [comment]
I am looking at my only poetry based projects, but they haven't got a src-based layout yet. Other than that they are quite simple.

```toml
[tool.poetry]
name = "packagename"
version = "1.0.0"
description = ""
authors = []
license = ""
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
```

It seems your dev dependencies have .group in it, mine doesn't

I haven't done any of this with mine:

```toml
packages = [
  { include = "thread", from = "src" },
  { include = "thread/py.typed", from = "src" },
]
include = [{ path = "tests", format = "sdist" }]
```

I was thinking, perhaps try regenerating the poetry lockfile???

**Comment by robvdl** [comment]
Also maybe the poetry version, I was using poetry 1.5.1

**Comment by caffeine-addictt** [comment]
Ah, that may be it.  I'm running poetry 1.7.1 here and `poetry lock` only updates the ruff dependency.

**Comment by robvdl** [comment]
I'm updating my poetry now, I had it installed globally

**Comment by robvdl** [comment]
I upgraded poetry and still no luck. It installs, but it doesn't install anything.

image

**Comment by robvdl** [comment]
pip freeze should list the packages that installed but it isn't, I'll try deleting and regenerating the lockfile

**Comment by robvdl** [comment]
deleting and regenerating the lockfile doesn't fix it sadly

**Comment by caffeine-addictt** [comment]
Thats odd
image

**Comment by robvdl** [comment]
I'm just reading this now https://browniebroke.com/blog/convert-existing-poetry-to-src-layout/

**Comment by robvdl** [comment]
I'm starting to think Poetry hates src-based layout but I'm not sure that is it.

**Comment by caffeine-addictt** [comment]
I'm not too sure if removing `py.typed` explicitly will place it in dist and be sufficient.

**Comment by robvdl** [comment]
I am stumped, I've already tried all those things and it had no effect, so I've reversed them again anyway.

I have never seen such a thing in my life. I also tried moving it up out of the src directory, but it had no effect.

**Comment by robvdl** [comment]
What is CITATION.cff it has a typo `reposistory-artifact: https://pypi.org/project/thread`

repostitory, not sure if that would do it

**Comment by caffeine-addictt** [comment]
CITATION.cff is for citing the repository
image

**Comment by robvdl** [comment]
I see why it isn't installing anything, is because (if you run it with -vvv) for very verbose you'll notice it won't bother installing typing-extensions because it doens't need it:

image

**Comment by caffeine-addictt** [comment]
It's using to proper virturalenv for me though

image

**Comment by robvdl** [comment]
Yeah that is the problem, Poetry has taken on managing the virtualenv now and it's getting in the way.

I hadn't come across this yet myself as I generally run stuff in Docker.

But this is a bit dissapointing because I just want Poetry to install into the current virtualenv but it is trying some weird cached one:


```
(thread) rob@rob-pc:~/Projects/thread$ poetry env info

Virtualenv
Python:         3.10.12
Implementation: CPython
Path:           /home/rob/.cache/pypoetry/virtualenvs/thread-zV_EQ1l7-py3.10
Executable:     /home/rob/.cache/pypoetry/virtualenvs/thread-zV_EQ1l7-py3.10/bin/python
Valid:          True

Base
Platform:   linux
OS:         posix
Python:     3.10.12
Path:       /usr
Executable: /usr/bin/python3.10
```

**Comment by robvdl** [comment]
Check this out then, I delete the env and it falls back to the right one (/home/rob/.virtualenvs/thread)

```
(thread) rob@rob-pc:~/Projects/thread$ poetry env remove --all
Deleted virtualenv: /home/rob/.cache/pypoetry/virtualenvs/thread-zV_EQ1l7-py3.10
(thread) rob@rob-pc:~/Projects/thread$ poetry env info

Virtualenv
Python:         3.10.12
Implementation: CPython
Path:           /home/rob/.virtualenvs/thread
Executable:     /home/rob/.virtualenvs/thread/bin/python
Valid:          True

Base
Platform:   linux
OS:         posix
Python:     3.10.12
Path:       /usr
Executable: /usr/bin/python3.10
```

**Comment by robvdl** [comment]
and now it works (after running `poetry env remove --all`)

image

But remember I also upgraded Poetry in between

**Comment by robvdl** [comment]
So poetry was trying to manage it's own env rather than installing into the env I gave it and that meant it only "looked" like nothing was installing.

**Comment by caffeine-addictt** [comment]
Seems like quite the troublesome feature of poetry

**Comment by caffeine-addictt** [comment]
I guess for the time being, tests can keep using `pip install .` for the time being unless you've already figured it out

**Comment by robvdl** [comment]
I'm not sure where to go from here. I'll leave this PR open but it feels running `pip install .` in CI was a hack.

I'm not sure if running `poetry env remove --all` in CI is such a great thing either, feels equally as much of a hack to me.

But you may want to look at that cherry picking typo in CITATION.cff if you want at least.

**Comment by caffeine-addictt** [comment]
Yea agreed. I'll co-author in another commit.

**Comment by caffeine-addictt** [comment]
Oh my god, I merged to wrong PR 🤣

**Comment by caffeine-addictt** [comment]
You can create another PR and reference this in the future. Apologies for the inconvenience 🥲

**Comment by robvdl** [comment]
Well it's not that bad, that branch was working.

**Pull request merged**
